#INCLUDE "pe.inc"

VAL la.ctrl.kill    IS pe.ctrl.kill    :
VAL la.ctrl.reset   IS pe.ctrl.reset   :
VAL la.ctrl.init    IS pe.ctrl.init    :
VAL la.ctrl.learn   IS pe.ctrl.learn   :
VAL la.ctrl.operate IS pe.ctrl.operate :
VAL la.ctrl.load    IS pe.ctrl.load    :
VAL la.ctrl.save    IS pe.ctrl.save    :

VAL la.ctrl.change.learning.rate IS 6(INT16) :

VAL no.input IS 132 :
VAL no.sample IS 10 :
VAL no.pe IS no.sample :
